stages:
  - deploy

pages:
  stage: deploy
  only:
    - master
    - development
    - doc_generation
  before_script:
    - export PATH="$PATH:/usr/lib/dart/bin"
    - export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"
    - export PATH="$PATH":"/snap/flutter/current/bin"
    - export FLUTTER_ROOT=$HOME/snap/flutter/common/flutter
    - flutter pub global activate dartdoc
  script:
    - dartdoc
    - cp -r doc/api public
  artifacts:
    paths:
      - public
