stages:
  - test
  - build
flutter_test:
  stage: test
  before_script:
    - export PATH="$PATH:/usr/local/bin/flutter/bin"
    - export ANDROID_HOME=/usr/local/bin/android-sdk/
    - export ANDROID_SDK_ROOT=/usr/local/bin/android-sdk/
    - export PATH=$PATH:$ANDROID_HOME/tools/bin
    - export JAVA_HOME=/usr/local/bin/jdk8u275-b01/
  script:
    - whoami
    #- flutter test
flutter_build_android:
  stage: build
  before_script:
    - export PATH="$PATH:/usr/local/bin/flutter/bin"
    - export ANDROID_HOME=/usr/local/bin/android-sdk/
    - export ANDROID_SDK_ROOT=/usr/local/bin/android-sdk/
    - export PATH=$PATH:$ANDROID_HOMEtools/bin
    - export JAVA_HOME=/usr/local/bin/jdk8u275-b01/
    - whoami
    - echo $PATH
    - flutter packages get
    - flutter clean
  script:
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
