stages:
  - test
  - build
flutter_test:
  stage: test
  before_script:
    - export PATH="$PATH:/usr/local/bin/flutter/bin"
    - export ANDROID_HOME=/usr/local/bin/android-sdk/
    - export ANDROID_SDK_ROOT=/usr/local/bin/android-sdk/
    - export PATH=$PATH:$ANDROID_HOME/tools/bin
    - export JAVA_HOME=/usr/local/bin/jdk8u275-b01/
    - whoami
    - echo $PATH
  script:
    - flutter test
flutter_build_android:
  stage: build
  before_script:
    - export PATH="$PATH:/usr/local/bin/flutter/bin"
    - export ANDROID_HOME=/usr/local/bin/android-sdk/
    - export ANDROID_SDK_ROOT=/usr/local/bin/android-sdk/
    - export PATH=$PATH:$ANDROID_HOMEtools/bin
    - export JAVA_HOME=/usr/local/bin/jdk8u275-b01/
    - whoami
    - echo $PATH
    - pwd
    - flutter packages get
    - flutter doctor -v
  script:
    - flutter build appbundle --target-platform android-arm,android-arm64,android-x64 -v
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
