stages:
  - test
  - build
flutter_test:
  stage: test
  before_script:
    - whoami
    - echo $PATH
    - pwd
    - flutter doctor -v
  script:
    - flutter test

build_android_release:
  stage: build
  before_script:
    - whoami
    - echo $PATH
    - flutter packages get
    - flutter clean
    - flutter doctor --android-licenses
    - flutter doctor
    - pwd
  script:
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/
