stages:
  - test
  - build
  - analyze
flutter_test:
  stage: test
  before_script:
    - whoami
    - echo $PATH
    - pwd
    - flutter doctor -v
  script:
    - flutter test

build_android_release:
  stage: build
  before_script:
    - whoami
    - echo $PATH
    - flutter packages get
    - flutter clean
    - flutter doctor --android-licenses
    - flutter doctor
    - pwd
  script:
    - flutter build appbundle --debug
  artifacts:
    paths:
      - build/app/outputs/

analyze:sonarqube:
  image: sonarsource/sonar-scanner-cli:latest
  stage: analyze
  allow_failure: true
  only:
    - master
    - release
    - development
    - sonar-cube
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
variables:
  SONAR_HOST_URL: ${CI_SONARQUBE_HOST_URL}
  SONAR_TOKEN: ${CI_SONARQUBE_TOKEN}
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
cache:
  key: ${CI_JOB_NAME}
  paths:
    - .sonar/cache